In [2]:
import torch
import pandas as pd
import numpy as np
import  matplotlib.pyplot as plt
print(torch.__version__)

2.1.2


In [4]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [8]:
# get tensor back as python int
scalar.item()

7

In [11]:
# vector

vector = torch.tensor([7,7,8])
vector

tensor([7, 7, 8])

In [12]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([3])

In [16]:
# MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [17]:
MATRIX.ndim

2

In [18]:
MATRIX[0]

tensor([7, 8])

In [19]:
MATRIX[1]

tensor([ 9, 10])

In [20]:
MATRIX.shape

torch.Size([2, 2])

In [21]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

In [22]:
TENSOR.ndim

3

In [23]:
TENSOR.shape

torch.Size([1, 3, 3])

In [24]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [25]:
### random tensors

In [28]:
random_tensor = torch.rand(2,3)
random_tensor

tensor([[0.6822, 0.4863, 0.7486],
        [0.5645, 0.7563, 0.8119]])

In [30]:
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channels

In [31]:
#zeros and ones

In [33]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [34]:
random_tensor * zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [35]:
### creating a range of tensors

In [37]:
one_to_ten = torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
tensor = torch.tensor([3.0,6.0,9],
                        dtype=None, #datatype
                        device='mps', #cpu/gpu
                        requires_grad=False #want pytorch to track gradients
                        )

In [39]:
tensor

tensor([3., 6., 9.])

In [41]:
# tensor math

In [43]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [44]:
tensor * 10

tensor([10, 20, 30])

In [45]:
tensor * tensor

tensor([1, 4, 9])

In [47]:
torch.matmul(tensor,tensor)

tensor(14)