In [2]:
import torch
import pandas as pd
import numpy as np
import  matplotlib.pyplot as plt
print(torch.__version__)

2.1.2


In [4]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [8]:
# get tensor back as python int
scalar.item()

7

In [11]:
# vector

vector = torch.tensor([7,7,8])
vector

tensor([7, 7, 8])

In [12]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([3])

In [16]:
# MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [17]:
MATRIX.ndim

2

In [18]:
MATRIX[0]

tensor([7, 8])

In [19]:
MATRIX[1]

tensor([ 9, 10])

In [20]:
MATRIX.shape

torch.Size([2, 2])

In [21]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])