In [1]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

output = (
    inputs[0] * weights[0] +
    inputs[1] * weights[1] +
    inputs[2] * weights[2] +
    inputs[3] * weights[3] + bias
)

In [2]:
output

4.8

In [3]:
inputs = [1,2,3,2.5]

weights1 = [0.2, 0.8, -0.5, 1]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

outputs = [
    #neuron 1
    inputs[0]*weights1[0] +
    inputs[1]*weights1[1] +
    inputs[2]*weights1[2] +
    inputs[3]*weights1[3] + bias1,

    #neuron 2
    inputs[0]*weights2[0] +
    inputs[1]*weights2[1] +
    inputs[2]*weights2[2] +
    inputs[3]*weights2[3] + bias2,

    #neuron 3
    inputs[0]*weights3[0] +
    inputs[1]*weights3[1] +
    inputs[2]*weights3[2] +
    inputs[3]*weights3[3] + bias3

]

In [4]:
outputs

[4.8, 1.21, 2.385]

In [14]:
inputs = [1,2,3,2.5]
weights = [[0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]]
biases = [2,3,0.5]

#output of the current layer
layer_outputs = []

#for each neuron
for neuron_weight, neuron_bias in zip(weights, biases):
    neuronValue = 0
    for weight, input in zip(neuron_weight,inputs):
        neuronValue += input * weight  
    neuronValue += neuron_bias
    layer_outputs.append(neuronValue)

In [15]:
layer_outputs

[4.8, 1.21, 2.385]

In [5]:
inputs = [1,2,3,2.5]
weights = [[0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]]
biases = [2,3,0.5]

In [8]:
list(zip(weights, biases))[0]

([0.2, 0.8, -0.5, 1], 2)

In [11]:
list(zip(neuron_weight,inputs))

[(0.2, 1), (0.8, 2), (-0.5, 3), (1, 2.5)]

In [16]:
# using numpy

import numpy as np

inputs = [1.0,2.0,3.0,2.5]
weights = [0.2,0.8,-0.5,1.0]
bias = 2.0

In [17]:
outputs = np.dot(weights, inputs) + bias

In [18]:
outputs

4.8

In [22]:
inputs = [1.0,2.0,3.0,2.5]
weights = [[0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0,3.0,0.5]

layer_outputs = np.dot(weights,inputs) + biases

In [23]:
layer_outputs

array([4.8  , 1.21 , 2.385])

In [27]:
#transpose 

a = [1,2,3]
b = [2,3,4]

a = np.array([a])
b = np.array([b]).T

print(np.dot(a,b))

[[20]]


In [30]:
inputs = [[1.0,2.0,3.0,2.5], #3x4
          [2.0,5.0,-1.0,2.0],
          [-1.5,2.7,3.3,-0.8]]

weights = [[0.2, 0.8, -0.5, 1], #3x4
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]]

biases = [2.0,3.0,0.5] #1x3

outputs = np.dot(inputs,np.array(weights).T) + biases

In [31]:
outputs

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

In [39]:
#adding a layer
inputs = [[1.0,2.0,3.0,2.5], #3x4
          [2.0,5.0,-1.0,2.0],
          [-1.5,2.7,3.3,-0.8]]

weights = [[0.2, 0.8, -0.5, 1], #3x4
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]]

weights2 = [[0.1, -0.14, 0.5], #3x3
    [-0.5, 0.12, -0.33],
    [-0.44, 0.73, -0.13]]

biases = [2.0,3.0,0.5] #1x3

biases2 = [-1,2,-0.5]

layer1_outputs = np.dot(inputs, np.array(weights).T) + biases
layer2_outputs = np.dot(layer1_outputs,np.array(weights2).T) + biases2

In [40]:
layer2_outputs

array([[ 0.5031 , -1.04185, -2.03875],
       [ 0.2434 , -2.7332 , -5.7633 ],
       [-0.99314,  1.41254, -0.35655]])

In [36]:
np.array(weights2).shape

(3, 3)