In [1]:
#relu activation function
#rectified linear activiation function

inputs = [0,2,-1,3.3,-2.7,1.1,2.2,-100]
output = []
for i in inputs:
    if i > 0:
        output.append(i)
    else:
        output.append(0)
print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [2]:
# or can be the max
inputs = [0,2,-1,3.3,-2.7,1.1,2.2,-100]
output = []
for i in inputs:
    output.append(max(0,i))

print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [3]:
#numpy
import numpy as np

inputs = [0,2,-1,3.3,-2.7,1.1,2.2,-100]
output = np.maximum(0,inputs)
print(output)


[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


In [4]:
#relu activation
class Activation_ReLU:

    #forward pass
    def forward(self,inputs):
        #calculate output values from input
        self.output = np.maximum(0,inputs)

In [5]:
#softmax

layer_outputs = [4.8,1.21,2.385]
E = 2.71828182846

exp_values = []
for output in layer_outputs:
    exp_values.append(E ** output)
print('exponentiated values:')
print(exp_values)

exponentiated values:
[121.51041751893969, 3.3534846525504487, 10.85906266492961]


In [6]:
norm_base = sum(exp_values)
norm_values = []
for value in exp_values:
    norm_values.append(value/norm_base)
print("normalized exponentiated values:")
print(norm_values)
print('Sum of normalized values:',sum(norm_values))

normalized exponentiated values:
[0.8952826639573506, 0.024708306782070668, 0.08000902926057876]
Sum of normalized values: 1.0


In [7]:
#numpy implementation
import numpy as np

layer_outputs = [4.8,1.21,2.385]
exp_values = np.exp(layer_outputs)
print('exponentiated values: ')
print(exp_values)

norm_values = exp_values / np.sum(exp_values)
print(norm_values)



exponentiated values: 
[121.51041752   3.35348465  10.85906266]
[0.89528266 0.02470831 0.08000903]


In [8]:
layer_outputs = np.array([[4.8,1.21,2.385],
                          [8.9,-1.1,0.2],
                          [1.41,1.051,0.026]
                          ])

In [12]:
np.sum(layer_outputs,axis=1,keepdims=True)

array([[8.395],
       [8.   ],
       [2.487]])