In [1]:
import math

softmax_output = [0.7,0.1,0.2]
target_output = [1,0,0]

loss = -(math.log(softmax_output[0])*target_output[0]+
         math.log(softmax_output[1])*target_output[1]+
         math.log(softmax_output[2])*target_output[2]
         )
print(loss)

0.35667494393873245


In [16]:
import numpy as np
softmax_output = np.array([[0.7,0.1,0.2],
                  [0.1,0.5,0.4],
                  [0.02,0.9,0.08]])
class_targets = np.array([0,1,1])

#probabilities for target values - onkly if categorical labels
if len(class_targets.shape) == 1:
    correct_confidences = softmax_output[
        range(len(softmax_output)),
        class_targets
    ]
#mask values - only for one-hot encoded labels
elif len(class_targets.shape) == 2:
    correct_confidences = np.sum(softmax_output*class_targets,axis = 1)

#losses
neg_log = -np.log(correct_confidences)
average_loss = np.mean(neg_log)
print(average_loss)

0.38506088005216804


In [15]:
class_targets = np.array([0,1,1])
class_targets.shape

(3,)

In [10]:
print(softmax_output[[class_targets],class_targets])

[[0.7 0.5 0.5]]


In [11]:
print(softmax_output[range(len(softmax_output)),class_targets])

[0.7 0.5 0.9]


In [12]:
print(-np.log(softmax_output[range(len(softmax_output)),class_targets]))

[0.35667494 0.69314718 0.10536052]


In [13]:
neg_loss = -np.log(softmax_output[range(len(softmax_output)),class_targets])
average_loss = np.mean(neg_loss)
print(average_loss)

0.38506088005216804


In [17]:
#accuracy
import numpy as np

#probabilities of 3 samples
softmax_outputs = np.array([[0.7,0.1,0.2],
                  [0.1,0.5,0.4],
                  [0.02,0.9,0.08]])
class_targets = np.array([0,1,1])

predictions = np.argmax(softmax_outputs,axis=1)

In [18]:
predictions

array([0, 1, 1])